config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/about'

  resources :companies do
    resources :reservations
    resources :buildings
  end

end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :company
  has_many :meeting_rooms, inverse_of: :building, dependent: :destroy

  accepts_nested_attributes_for :meeting_rooms, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  def index
    @buildings = @company.buildings.all
  end

  def show
    @meeting_rooms = @building.meeting_rooms
  end

  def new
    @building = @company.buildings.build
  end

  def edit
    @building = @company.buildings.find(params[:id])
  end

  def create
    @building = @company.buildings.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to company_path(@company), notice: 'Building and Meeting Rooms were successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to company_path(@company), notice: 'Building and Meeting Rooms were successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to company_path(@company), notice: 'Building was successfully destroyed.' }
    end
  end

  private
  def set_company
    @company = current_user.companies.find(params[:company_id])
  end

  def set_building
    @building = @company.buildings.find(params[:id])
  end

  def building_params
    params.require(:building).permit(
      :name,
      meeting_rooms_attributes: [:id, :name, :capacity, :_destroy,
                                 equipment_attributes: [:id, :_destroy, :name],
      equipment_meeting_rooms_attributes: [:id, :name, :_destroy, :equipment_id, equipment_attributes: [:id, :_destroy, :name]]]
    )
  end
end

app/views/buildings/_building.html.haml
%tr
  %td= link_to building.name, company_building_path(@company, building)
  %td= link_to building.meeting_rooms.count, company_building_path(@company, building)
  %td.text-right
    = link_to edit_company_building_path(@company, building), class: "btn btn-warning btn-sm" do
      %i.glyphicon.glyphicon-pencil
    = link_to company_building_path(@company, building), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" do
      %i.glyphicon.glyphicon-remove-sign

app/views/buildings/_equipment_fields.html.haml
.nested-fields.form-inline{:style => "display: inline;"}
= f.input :name, :placeholder => 'equipment name', :label => false

app/views/buildings/_equipment_meeting_room_fields.html.haml
.nested-fields.equipment-meeting-room-fields

  .well.well-compact
    .form-inline
      .equipment_from_list{:style => "display: inline;"}
        = f.association :equipment, collection: Equipment.order(:name), prompt: 'Choose an existing equipment', label: false
      = link_to_add_association 'or create a new equipment', f, :equipment, class: 'add-equipment'
      = link_to_remove_association f, class: 'remove-equipment btn btn-danger btn-xs' do
        .glyphicon.glyphicon-remove-sign

app/views/buildings/_form.html.haml
= simple_form_for [@company, @building] do |f|
  = f.error_notification
  = f.input :name
  %h3 Meeting Rooms
  #meeting_rooms
    = f.simple_fields_for :meeting_rooms do |meeting_room|
      = render 'meeting_room_fields', f: meeting_room
    .links
      = link_to_add_association 'add meeting room', f, :meeting_rooms
  = f.button :submit, class: 'btn btn-primary', disable_with: 'Please wait...'

  = link_to 'Cancel', company_buildings_path(@company), class: 'btn btn-link'

app/views/buildings/_meeting_room_fields.html.haml
.nested-fields.well.well-compact
  .form-inline
    = f.input :name, :placeholder => 'meeting room name', class: 'form-control'
    = f.input :capacity, :placeholder => 'add capacity (people)', class: 'form-control'
    = link_to_remove_association f, data: {:confirm => 'are you sure?'}, class: 'btn btn-danger btn-sm' do
      .glyphicon.glyphicon-remove
  %h4 Equipment
  .well.well-compact
    .equipment_meeting_room
      = f.simple_fields_for :equipment_meeting_rooms do |equipment_meeting_room|
        = render 'equipment_meeting_room_fields', :f => equipment_meeting_room
      .links
      = link_to_add_association f, :equipment_meeting_rooms, class: 'btn btn-success btn-sm' do
        .glyphicon.glyphicon-plus-sign  add equipment

app/views/buildings/edit.html.haml
%h1 Edit building
= render 'form', building: @building

app/views/buildings/new.html.haml
%h1 New building

app/views/buildings/show.html.haml
= fa_stacked_icon "group inverse", base: "circle", class: "fa-2x pull-left"
%h1 Meeting Rooms
- if @building.meeting_rooms.exists?
  %div.panel.panel-info
    %div.panel-heading Meeting Rooms list
    %table.table.table-hover
      %thead
        %tr
          %th.offset Name 
          %th Capacity
      %tbody
        = render @meeting_rooms
    %div.panel-footer.text-right
- else
  = render "shared/empty_list"