config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/about'

  resources :companies do
    resources :reservations
    resources :buildings
  end

end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :buildings, dependent: :destroy

  validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def show
    load_company
    load_company_buildings
  end

  def new
    build_company
  end

  def create
    build_company
    save_company or render 'new'
  end

  def edit
    load_company
    build_company
  end

  def update
    load_company
    build_company
    save_company or render 'edit'
  end

  def destroy
    load_company
    @company.destroy
    redirect_to root_path
  end

  private

  def load_company
    @company = company_scope.find(params[:id])
  end

  def load_company_buildings
    @buildings = @company.buildings
  end

  def build_company
    @company ||= company_scope.build
    @company.attributes = company_params
  end

  def save_company
    if @company.save
      redirect_to root_path
    end
  end

  def company_params
    company_params = params[:company]
    company_params ? company_params.permit(:name, :user_id) : {}
  end

  def company_scope
    current_user.companies.all
  end
end

app/views/companies/_form.html.haml
= simple_form_for(@company) do |f|
  = f.error_notification
  = f.input :name
  = f.button :submit

app/views/companies/edit.html.haml
%h1 Edit Company

= render 'form', company: @company

app/views/companies/index.html.haml
= fa_stacked_icon "industry inverse", base: "circle", class: "fa-2x pull-left"
%h1 Companies
- if current_user.companies.exists?
  %div.panel.panel-info
    %div.panel-heading Companies list
    %table.table.table-hover
      %thead
        %tr
          %th.offset Name 
          %th
      %tbody
      - current_user.companies.each do |company|
        %tr
          %td= link_to company.name, company_path(company)
          %td.text-right
            = link_to company, class: "btn btn-success btn-sm" do
              %i.glyphicon.glyphicon-eye-open
            = link_to edit_company_path(company), class: "btn btn-warning btn-sm" do
              %i.glyphicon.glyphicon-pencil
            = link_to company, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" do
              %i.glyphicon.glyphicon-remove-sign
    %div.panel-footer.text-right
      = link_to new_company_path, class: "btn btn-primary" do
        %i.glyphicon.glyphicon-plus-sign
        Add a new Company
- else
  = render "shared/empty_list"
  = link_to new_company_path, class: "btn btn-danger" do
    %i.glyphicon.glyphicon-plus-sign
    Add your first Company!

app/views/companies/new.html.haml
%h1 New Company

= render 'form', company: @company

app/views/companies/show.html.haml
= fa_stacked_icon "building inverse", base: "circle", class: "fa-2x pull-left"
%h1= @company.name
- if @buildings.exists?
  %div.panel.panel-info
    %div.panel-heading Buildings list
    %table.table.table-hover
      %thead
        %tr
          %th.offset Building Name 
          %th Meeting Rooms
          %th
      %tbody
        = render @buildings
    %div.panel-footer.text-right
      = link_to new_company_building_path(@company), class: "btn btn-primary" do
        %i.glyphicon.glyphicon-plus-sign
        Add a new Building
  = link_to company_reservations_path(@company), class: "btn btn-success" do
    %i.glyphicon.glyphicon-plus-sign
    Add a reservation

- else
  = render "shared/empty_list"
  = link_to new_company_building_path(@company), class: "btn btn-danger" do
    %i.glyphicon.glyphicon-plus-sign
    Add your first Building!