config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'auth/callbacks' }

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/about'

  resources :companies do
    resources :reservations
    resources :buildings
  end

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "EZ-Meetings", root_path, class: "navbar-brand"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => root_path} Home
        - if user_signed_in? && current_user.companies.exists?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Companies
              %span.caret
            %ul.dropdown-menu
              %li= link_to "Companies list", companies_path
              %li= link_to "Add a new Company", new_company_path
        %li= link_to "About", pages_about_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to current_user.email, edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign In", new_user_session_path
    / /.nav-collapse

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title EZ-Meetings
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Kaushan+Script", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Quicksand", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render "layouts/header"
    .container
      = render "shared/flash_messages"
      = yield